apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  version: "0.1.1"
  workloads:
    - name: podtato-head-frontend
      version: 0.1.0
  preDeploymentEvaluations:
    - app-pre-deploy-eval-1
