apiVersion: lifecycle.keptn.sh/v1alpha3
kind: KeptnApp
metadata:
  name: podtato-head
  namespace: podtato-kubectl
spec:
  version: "1.0.0"
  workloads:
    - name: podtato-head-frontend
      version: 0.1.0
